# Generated by Django 2.1.2 on 2018-10-14 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_type', models.CharField(choices=[('Results', 'Results'), ('Tee Times', 'Tee Times'), ('Registration', 'Registration'), ('Media', 'Media'), ('Other', 'Other')], max_length=40, verbose_name='Link Type')),
                ('url', models.CharField(max_length=240, verbose_name='Full Url')),
            ],
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'Championship or Other Event', 'verbose_name_plural': 'Championships and Other Events'},
        ),
        migrations.AlterModelOptions(
            name='historicalevent',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Championship or Other Event'},
        ),
        migrations.AddField(
            model_name='eventlink',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='urls', to='events.Event', verbose_name='Event'),
        ),
    ]
