# Generated by Django 5.1.4 on 2025-01-04 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventpoints',
            options={'ordering': ['event', 'place']},
        ),
        migrations.AlterModelOptions(
            name='eventpolicy',
            options={'ordering': ['event', 'order']},
        ),
        migrations.AlterModelOptions(
            name='historicalevent',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Event', 'verbose_name_plural': 'historical Events'},
        ),
        migrations.AlterField(
            model_name='historicalevent',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
    ]
