# Generated by Django 2.1.2 on 2018-10-04 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Award Name')),
                ('description', models.TextField(verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='AwardWinner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Year')),
                ('winner', models.CharField(max_length=100, verbose_name='Award Winner')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('award', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='winners', to='events.Award', verbose_name='Award')),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tournament Name')),
                ('description', models.TextField(verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='TournamentWinner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Year')),
                ('location', models.CharField(max_length=100, verbose_name='Location')),
                ('winner', models.CharField(max_length=100, verbose_name='Tournament Winner')),
                ('winner_club', models.CharField(blank=True, max_length=100, verbose_name='Club')),
                ('co_winner', models.CharField(max_length=100, verbose_name='Tournament Winner')),
                ('co_winner_club', models.CharField(blank=True, max_length=100, verbose_name='Club')),
                ('flight_or_division', models.CharField(choices=[('Championship', 'Championship'), ('Senior', 'Senior'), ('Super Senior', 'Super Senior'), ('First Flight', 'First Flight'), ('Second Flight', 'Second Flight'), ('Third Flight', 'Third Flight'), ('Fourth Flight', 'Fourth Flight'), ('Fifth Flight', 'Fifth Flight'), ('Sixth Flight', 'Sixth Flight')], max_length=20, verbose_name='Flight or Division')),
                ('score', models.CharField(blank=True, max_length=20, verbose_name='Score')),
                ('is_net', models.BooleanField(default=False, verbose_name='Score is a Net Score')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='winners', to='events.Tournament', verbose_name='Tournament')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='tournament',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='events.Tournament', verbose_name='Tournament'),
        ),
        migrations.AddField(
            model_name='historicalevent',
            name='tournament',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='events.Tournament'),
        ),
    ]
