# Generated by Django 2.1.2 on 2018-10-14 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20181014_1516'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventDivision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('division', models.CharField(choices=[('Championship', 'Championship'), ('Net', 'Net'), ('Super-Senior', 'Super-Senior'), ('Senior', 'Senior'), ('Flighted', 'Flighted')], max_length=20, verbose_name='Division')),
            ],
        ),
        migrations.CreateModel(
            name='EventFee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee_type', models.CharField(max_length=30, verbose_name='Fee Type')),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Amount')),
            ],
        ),
        migrations.AlterModelOptions(
            name='tournament',
            options={'verbose_name': 'Championship Overview', 'verbose_name_plural': 'Championship Overviews'},
        ),
        migrations.AlterModelOptions(
            name='tournamentwinner',
            options={'verbose_name': 'Championship Winner', 'verbose_name_plural': 'Championship Winners'},
        ),
        migrations.AlterField(
            model_name='event',
            name='tournament',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='events.Tournament', verbose_name='Championship'),
        ),
        migrations.AlterField(
            model_name='eventlink',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='events.Event', verbose_name='Event'),
        ),
        migrations.AlterField(
            model_name='tournamentwinner',
            name='co_winner',
            field=models.CharField(blank=True, max_length=100, verbose_name='Winner'),
        ),
        migrations.AlterField(
            model_name='tournamentwinner',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='winners', to='events.Tournament', verbose_name='Championship'),
        ),
        migrations.AlterField(
            model_name='tournamentwinner',
            name='winner',
            field=models.CharField(max_length=100, verbose_name='Winner'),
        ),
        migrations.AddField(
            model_name='eventfee',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fees', to='events.Event', verbose_name='Event'),
        ),
        migrations.AddField(
            model_name='eventdivision',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='divisions', to='events.Event', verbose_name='Event'),
        ),
    ]
