# Generated by Django 2.1.2 on 2018-10-19 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20181014_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('T', 'Championship'), ('B', 'Banquet'), ('M', 'Meeting')], default='T', max_length=1, verbose_name='Event type'),
        ),
        migrations.AlterField(
            model_name='historicalevent',
            name='event_type',
            field=models.CharField(choices=[('T', 'Championship'), ('B', 'Banquet'), ('M', 'Meeting')], default='T', max_length=1, verbose_name='Event type'),
        ),
    ]
