# Generated by Django 2.1.2 on 2018-11-10 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20181019_0825'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='short_name',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Short name for menus'),
        ),
        migrations.AddField(
            model_name='historicalevent',
            name='short_name',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Short name for menus'),
        ),
    ]
