# Generated by Django 2.1.2 on 2018-12-08 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20181110_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentwinner',
            name='is_match',
            field=models.BooleanField(default=False, verbose_name='Match Play'),
        ),
        migrations.AlterField(
            model_name='tournamentwinner',
            name='co_winner',
            field=models.CharField(blank=True, max_length=100, verbose_name='Winner (Opponent for Match Play)'),
        ),
    ]
