# Generated by Django 2.1.2 on 2018-12-26 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_auto_20181208_0914'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'Championship or Competition', 'verbose_name_plural': 'Championships and Competitions'},
        ),
        migrations.AlterModelOptions(
            name='historicalevent',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Championship or Competition'},
        ),
        migrations.AlterModelOptions(
            name='tournament',
            options={'verbose_name': 'Competition', 'verbose_name_plural': 'Competitions'},
        ),
        migrations.AlterModelOptions(
            name='tournamentwinner',
            options={'verbose_name': 'Competition Winner', 'verbose_name_plural': 'Competition Winners'},
        ),
        migrations.AlterField(
            model_name='tournamentwinner',
            name='flight_or_division',
            field=models.CharField(max_length=20, verbose_name='Flight or Division'),
        ),
    ]
