# Generated by Django 2.1.2 on 2018-12-28 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_auto_20181226_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='awardwinner',
            name='notes',
            field=models.CharField(blank=True, max_length=140, null=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='tournamentwinner',
            name='notes',
            field=models.CharField(blank=True, max_length=140, null=True, verbose_name='Notes'),
        ),
    ]
