# Generated by Django 2.1.5 on 2020-01-19 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_auto_20190101_1912'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='awardwinner',
            options={'ordering': ['-year']},
        ),
        migrations.AlterModelOptions(
            name='tournament',
            options={'verbose_name': 'Tournament', 'verbose_name_plural': 'Tournaments'},
        ),
        migrations.AlterModelOptions(
            name='tournamentwinner',
            options={'ordering': ['-year'], 'verbose_name': 'Tournament Winner', 'verbose_name_plural': 'Tournament Winners'},
        ),
        migrations.AddField(
            model_name='tournament',
            name='system_name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='System name'),
        ),
        migrations.AlterField(
            model_name='historicalevent',
            name='location',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='clubs.GolfCourse', verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='historicalevent',
            name='tournament',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='events.Tournament', verbose_name='Championship'),
        ),
        migrations.AlterField(
            model_name='tournamentwinner',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='winners', to='events.Tournament', verbose_name='Tournament'),
        ),
    ]
