# Generated by Django 2.1.5 on 2020-03-12 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_auto_20200119_1346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventdivision',
            name='event',
        ),
        migrations.RemoveField(
            model_name='eventfee',
            name='event',
        ),
        migrations.RemoveField(
            model_name='event',
            name='maximum_signup_group_size',
        ),
        migrations.RemoveField(
            model_name='event',
            name='minimum_signup_group_size',
        ),
        migrations.RemoveField(
            model_name='event',
            name='registration_maximum',
        ),
        migrations.RemoveField(
            model_name='event',
            name='registration_type',
        ),
        migrations.RemoveField(
            model_name='event',
            name='short_name',
        ),
        migrations.RemoveField(
            model_name='historicalevent',
            name='maximum_signup_group_size',
        ),
        migrations.RemoveField(
            model_name='historicalevent',
            name='minimum_signup_group_size',
        ),
        migrations.RemoveField(
            model_name='historicalevent',
            name='registration_maximum',
        ),
        migrations.RemoveField(
            model_name='historicalevent',
            name='registration_type',
        ),
        migrations.RemoveField(
            model_name='historicalevent',
            name='short_name',
        ),
        migrations.DeleteModel(
            name='EventDivision',
        ),
        migrations.DeleteModel(
            name='EventFee',
        ),
    ]
