# Generated by Django 2.1.5 on 2020-04-05 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_auto_20200312_0748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournamentwinner',
            name='winner_club',
            field=models.CharField(blank=True, max_length=100, verbose_name='Club'),
        ),
    ]
