# Generated by Django 2.1.5 on 2020-04-21 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_auto_20200405_0813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='awardwinner',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='tournamentwinner',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
    ]
