# Generated by Django 3.0.6 on 2020-05-10 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_auto_20200420_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('T', 'Championship'), ('B', 'Banquet'), ('M', 'Meeting'), ('C', 'Canceled'), ('P', 'Postponed')], default='T', max_length=1, verbose_name='Event type'),
        ),
        migrations.AlterField(
            model_name='historicalevent',
            name='event_type',
            field=models.CharField(choices=[('T', 'Championship'), ('B', 'Banquet'), ('M', 'Meeting'), ('C', 'Canceled'), ('P', 'Postponed')], default='T', max_length=1, verbose_name='Event type'),
        ),
    ]
