# Generated by Django 3.0.6 on 2020-05-10 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SeasonSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_calendar_year', models.IntegerField(verbose_name='Default year for the event calendar')),
                ('match_play_year', models.IntegerField(verbose_name='Default year for match play')),
                ('member_club_year', models.IntegerField(verbose_name='Default year for club membership')),
                ('membership_dues', models.IntegerField(default=100, verbose_name='Membership dues')),
                ('match_play_divisions', models.CharField(default='', max_length=150, verbose_name='Match play divisions')),
                ('match_play_groups', models.CharField(default='', max_length=250, verbose_name='Match play groups')),
                ('match_play_finalized', models.BooleanField(default=False, verbose_name='Match play teams are final')),
                ('match_play_forfeit_percentage', models.DecimalField(decimal_places=1, default=66.6, max_digits=3, verbose_name='Forfeit winner percentage')),
            ],
            options={
                'verbose_name': 'Season Settings',
                'verbose_name_plural': 'Season Settings',
            },
        ),
    ]
