# Generated by Django 2.1.2 on 2018-10-20 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalmember',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='historicalmember',
            name='ghin',
        ),
        migrations.RemoveField(
            model_name='member',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='member',
            name='ghin',
        ),
    ]
