# Generated by Django 2.1.2 on 2018-12-28 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20181020_1840'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seasonsettings',
            name='reg_event',
        ),
        migrations.RemoveField(
            model_name='seasonsettings',
            name='year',
        ),
        migrations.AddField(
            model_name='seasonsettings',
            name='event_calendar_year',
            field=models.IntegerField(default=0, verbose_name='Default year for the event calendar'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seasonsettings',
            name='match_play_year',
            field=models.IntegerField(default=0, verbose_name='Default year for match play'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seasonsettings',
            name='member_club_year',
            field=models.IntegerField(default=0, verbose_name='Default year for club membership'),
            preserve_default=False,
        ),
    ]
