# Generated by Django 2.1.2 on 2019-01-01 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20181228_1353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalmember',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='historicalmember',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalmember',
            name='home_club',
        ),
        migrations.RemoveField(
            model_name='historicalmember',
            name='user',
        ),
        migrations.RemoveField(
            model_name='member',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='member',
            name='home_club',
        ),
        migrations.RemoveField(
            model_name='member',
            name='user',
        ),
        migrations.AddField(
            model_name='seasonsettings',
            name='membership_dues',
            field=models.IntegerField(default=100, verbose_name='Membership dues'),
        ),
        migrations.DeleteModel(
            name='HistoricalMember',
        ),
        migrations.DeleteModel(
            name='Member',
        ),
    ]
