# Generated by Django 2.1.2 on 2019-01-06 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190101_0838'),
    ]

    operations = [
        migrations.AddField(
            model_name='seasonsettings',
            name='match_play_finalized',
            field=models.BooleanField(default=False, verbose_name='Match play teams are final'),
        ),
    ]
