# Generated by Django 2.1.2 on 2019-01-12 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_seasonsettings_match_play_finalized'),
    ]

    operations = [
        migrations.AddField(
            model_name='seasonsettings',
            name='match_play_divisions',
            field=models.CharField(default='', max_length=150, verbose_name='Match play divisions'),
        ),
        migrations.AddField(
            model_name='seasonsettings',
            name='match_play_groups',
            field=models.CharField(default='', max_length=150, verbose_name='Match play groups'),
        ),
    ]
