# Generated by Django 2.1.2 on 2019-01-12 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20190112_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seasonsettings',
            name='match_play_groups',
            field=models.CharField(default='', max_length=250, verbose_name='Match play groups'),
        ),
    ]
