# Generated by Django 2.1.2 on 2019-01-13 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20190112_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='seasonsettings',
            name='match_play_forfeit_percentage',
            field=models.DecimalField(decimal_places=1, default=66.6, max_digits=3, verbose_name='Forfeit winner percentage'),
        ),
    ]
