# Generated by Django 2.1.2 on 2018-10-14 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalpolicy',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Policy'},
        ),
        migrations.AlterModelOptions(
            name='policy',
            options={'verbose_name': 'Policy', 'verbose_name_plural': 'Policies'},
        ),
        migrations.AlterField(
            model_name='historicalpolicy',
            name='policy_type',
            field=models.CharField(choices=[('LR', 'Local Rule'), ('CC', 'Code of Conduct'), ('AU', 'About Us'), ('SP', 'Senior Match Play'), ('MP', 'Match Play'), ('TN', 'Tournament'), ('TP', 'Tournament Player Information'), ('PP', 'Pace of Play'), ('OX', 'Other')], default='OX', max_length=2, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='policy_type',
            field=models.CharField(choices=[('LR', 'Local Rule'), ('CC', 'Code of Conduct'), ('AU', 'About Us'), ('SP', 'Senior Match Play'), ('MP', 'Match Play'), ('TN', 'Tournament'), ('TP', 'Tournament Player Information'), ('PP', 'Pace of Play'), ('OX', 'Other')], default='OX', max_length=2, verbose_name='Type'),
        ),
    ]
