# Generated by Django 5.1.4 on 2025-01-04 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalpolicy',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Policy', 'verbose_name_plural': 'historical Policies'},
        ),
        migrations.AlterField(
            model_name='historicalpolicy',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
    ]
