# Generated by Django 2.1.2 on 2018-10-20 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0002_auto_20181014_1645'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalpolicy',
            name='version',
        ),
        migrations.RemoveField(
            model_name='policy',
            name='version',
        ),
    ]
