# Generated by Django 2.1.2 on 2018-12-25 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicallandingpage',
            name='page_type',
            field=models.CharField(choices=[('H', 'Home'), ('T', 'Tournaments'), ('A', 'About the MPGA'), ('M', 'Match Play'), ('C', 'Member Clubs'), ('E', 'Club Editing')], max_length=1, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='page_type',
            field=models.CharField(choices=[('H', 'Home'), ('T', 'Tournaments'), ('A', 'About the MPGA'), ('M', 'Match Play'), ('C', 'Member Clubs'), ('E', 'Club Editing')], max_length=1, verbose_name='Type'),
        ),
    ]
