# Generated by Django 2.1.2 on 2018-12-28 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20181225_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicallandingpage',
            name='page_type',
            field=models.CharField(choices=[('H', 'Home'), ('B', 'Tournament Bids'), ('A', 'About the MPGA'), ('M', 'Match Play'), ('C', 'Member Clubs'), ('E', 'Club Editing'), ('CC', 'Code of Conduct')], max_length=2, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='page_type',
            field=models.CharField(choices=[('H', 'Home'), ('B', 'Tournament Bids'), ('A', 'About the MPGA'), ('M', 'Match Play'), ('C', 'Member Clubs'), ('E', 'Club Editing'), ('CC', 'Code of Conduct')], max_length=2, verbose_name='Type'),
        ),
    ]
