# Generated by Django 2.1.2 on 2018-12-28 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20181228_0739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicallandingpage',
            name='page_type',
            field=models.CharField(choices=[('H', 'Home'), ('B', 'Tournament Bids'), ('A', 'About the MPGA'), ('M', 'Match Play'), ('C', 'Member Clubs'), ('E', 'Club Editing'), ('CC', 'Code of Conduct'), ('OM', 'Our Mission')], max_length=2, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='page_type',
            field=models.CharField(choices=[('H', 'Home'), ('B', 'Tournament Bids'), ('A', 'About the MPGA'), ('M', 'Match Play'), ('C', 'Member Clubs'), ('E', 'Club Editing'), ('CC', 'Code of Conduct'), ('OM', 'Our Mission')], max_length=2, verbose_name='Type'),
        ),
    ]
