# Generated by Django 2.1.2 on 2019-01-13 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_auto_20181230_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicallandingpage',
            name='page_type',
            field=models.CharField(choices=[('H', 'Home'), ('B', 'Tournament Bids'), ('A', 'About the MPGA'), ('M', 'Match Play'), ('C', 'Member Clubs'), ('E', 'Club Editing'), ('CC', 'Code of Conduct'), ('OM', 'Our Mission'), ('EC', 'Executive Committee'), ('MP', 'Match Play Signup'), ('FQ', 'FAQ')], max_length=2, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='page_type',
            field=models.CharField(choices=[('H', 'Home'), ('B', 'Tournament Bids'), ('A', 'About the MPGA'), ('M', 'Match Play'), ('C', 'Member Clubs'), ('E', 'Club Editing'), ('CC', 'Code of Conduct'), ('OM', 'Our Mission'), ('EC', 'Executive Committee'), ('MP', 'Match Play Signup'), ('FQ', 'FAQ')], max_length=2, verbose_name='Type'),
        ),
    ]
