# Generated by Django 2.1.5 on 2020-04-21 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_auto_20190113_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicallandingpage',
            name='page_type',
            field=models.CharField(choices=[('H', 'Home'), ('B', 'Tournament Bids'), ('A', 'About the MPGA'), ('M', 'Match Play'), ('C', 'Member Clubs'), ('E', 'Club Editing'), ('R', 'Club Registration'), ('I', 'Individual Registration'), ('CC', 'Code of Conduct'), ('OM', 'Our Mission'), ('EC', 'Executive Committee'), ('MP', 'Match Play Signup'), ('FQ', 'FAQ')], max_length=2, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='page_type',
            field=models.CharField(choices=[('H', 'Home'), ('B', 'Tournament Bids'), ('A', 'About the MPGA'), ('M', 'Match Play'), ('C', 'Member Clubs'), ('E', 'Club Editing'), ('R', 'Club Registration'), ('I', 'Individual Registration'), ('CC', 'Code of Conduct'), ('OM', 'Our Mission'), ('EC', 'Executive Committee'), ('MP', 'Match Play Signup'), ('FQ', 'FAQ')], max_length=2, verbose_name='Type'),
        ),
    ]
