# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-21 20:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllContacts',
            fields=[
                ('vkey', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Club Name')),
                ('first_name', models.CharField(max_length=30, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=30, verbose_name='Last Name')),
                ('contact_type', models.CharField(max_length=3, verbose_name='Contact Type')),
                ('primary_phone', models.CharField(blank=True, max_length=20, verbose_name='Primary Phone')),
                ('alternate_phone', models.CharField(blank=True, max_length=20, verbose_name='Alternate Phone')),
                ('email', models.CharField(blank=True, max_length=250, verbose_name='Email')),
                ('role', models.CharField(max_length=30, verbose_name='Role')),
                ('is_primary', models.BooleanField(verbose_name='Primary')),
            ],
            options={
                'verbose_name_plural': 'All Contacts',
                'db_table': 'all_contacts_view',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PrimaryContacts',
            fields=[
                ('vkey', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Club Name')),
                ('first_name', models.CharField(max_length=30, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=30, verbose_name='Last Name')),
                ('contact_type', models.CharField(max_length=3, verbose_name='Contact Type')),
                ('primary_phone', models.CharField(blank=True, max_length=20, verbose_name='Primary Phone')),
                ('alternate_phone', models.CharField(blank=True, max_length=20, verbose_name='Alternate Phone')),
                ('email', models.CharField(blank=True, max_length=250, verbose_name='Email')),
                ('role', models.CharField(max_length=30, verbose_name='Role')),
                ('is_primary', models.BooleanField(verbose_name='Primary')),
            ],
            options={
                'verbose_name_plural': 'Primary Contacts',
                'db_table': 'club_contacts_view',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TeamCaptains',
            fields=[
                ('vkey', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Club Name')),
                ('first_name', models.CharField(max_length=30, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=30, verbose_name='Last Name')),
                ('contact_type', models.CharField(max_length=3, verbose_name='Contact Type')),
                ('primary_phone', models.CharField(blank=True, max_length=20, verbose_name='Primary Phone')),
                ('alternate_phone', models.CharField(blank=True, max_length=20, verbose_name='Alternate Phone')),
                ('email', models.CharField(blank=True, max_length=250, verbose_name='Email')),
                ('year', models.IntegerField(verbose_name='Golf Season')),
                ('group_name', models.CharField(max_length=20, verbose_name='Group')),
                ('is_senior', models.BooleanField(verbose_name='Senior')),
            ],
            options={
                'verbose_name_plural': 'Team Captains',
                'db_table': 'team_captains_view',
                'managed': False,
            },
        ),
    ]
