# Generated by Django 2.1.2 on 2018-10-05 02:51

from django.db import migrations, models
import django.db.models.deletion
import documents.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('T', 'Tournament'), ('B', 'Banquet'), ('M', 'Meeting'), ('P', 'Match Play'), ('F', 'Financial'), ('C', 'Communications'), ('O', 'Other')], max_length=1, verbose_name='Document Type')),
                ('year', models.IntegerField(blank=True, null=True, verbose_name='Golf Season')),
                ('title', models.CharField(max_length=120, verbose_name='Title')),
                ('file', models.FileField(upload_to=documents.models.document_directory_path, verbose_name='File')),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='documents', to='events.Event', verbose_name='Event')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.Document', verbose_name='Document')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_type', models.CharField(choices=[('G', 'Golf Course'), ('W', 'Tournament Winners'), ('T', 'Tournament Photos'), ('O', 'Other')], max_length=1, verbose_name='Type')),
                ('year', models.IntegerField(default=0, verbose_name='Golf Season')),
                ('title', models.CharField(max_length=120, verbose_name='Title')),
                ('raw_image', models.ImageField(upload_to=documents.models.photo_directory_path, verbose_name='Image')),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='events.Event', verbose_name='Event')),
            ],
        ),
        migrations.CreateModel(
            name='PhotoTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.Photo', verbose_name='Photo')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Tag')),
            ],
        ),
        migrations.AddField(
            model_name='phototag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.Tag', verbose_name='Tag'),
        ),
        migrations.AddField(
            model_name='documenttag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.Tag', verbose_name='Tag'),
        ),
    ]
