# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-24 19:38
from __future__ import unicode_literals

from django.db import migrations, models
import documents.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('EA', 'Event Application'), ('ER', 'Event Results'), ('TT', 'Event Tee Times'), ('SP', 'Season Points'), ('MM', 'Meeting Minutes'), ('MP', 'Match Play'), ('F', 'Financial Statements'), ('S', 'Newsletter'), ('O', 'Other')], max_length=2, verbose_name='Document Type')),
                ('year', models.IntegerField(default=0, verbose_name='Golf Season')),
                ('title', models.CharField(max_length=120, verbose_name='Title')),
                ('event', models.CharField(blank=True, max_length=120, verbose_name='Event')),
                ('file', models.FileField(upload_to=documents.models.document_directory_path, verbose_name='File')),
                ('last_update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Tag')),
            ],
        ),
        migrations.AddField(
            model_name='document',
            name='tags',
            field=models.ManyToManyField(to='documents.Tag'),
        ),
    ]
