# Generated by Django 4.0.1 on 2022-02-06 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['-year', '-last_update']},
        ),
    ]
