# Generated by Django 2.1.2 on 2018-11-10 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('T', 'Tournament'), ('R', 'Registration'), ('M', 'Meeting'), ('P', 'Match Play'), ('F', 'Financial'), ('C', 'Communications'), ('O', 'Other')], max_length=1, verbose_name='Document Type'),
        ),
    ]
