# Generated by Django 4.1.7 on 2023-03-26 21:52

from django.db import migrations, models
import documents.models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_alter_document_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('ByLaws', 'ByLaws'), ('Club Registration', 'Club Registration'), ('Registration', 'Registration'), ('Results', 'Results'), ('Agenda', 'Agenda'), ('Minutes', 'Minutes'), ('Match Play', 'Match Play'), ('Match Play Brackets', 'Match Play Brackets'), ('Financial', 'Financial'), ('Standing Orders', 'Standing Orders'), ('Tee Times', 'Tee Times'), ('Other', 'Other'), ('Hard Card', 'Hard Card')], max_length=20, verbose_name='Document Type'),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(null=True, upload_to=documents.models.document_directory_path, verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='historicaldocument',
            name='document_type',
            field=models.CharField(choices=[('ByLaws', 'ByLaws'), ('Club Registration', 'Club Registration'), ('Registration', 'Registration'), ('Results', 'Results'), ('Agenda', 'Agenda'), ('Minutes', 'Minutes'), ('Match Play', 'Match Play'), ('Match Play Brackets', 'Match Play Brackets'), ('Financial', 'Financial'), ('Standing Orders', 'Standing Orders'), ('Tee Times', 'Tee Times'), ('Other', 'Other'), ('Hard Card', 'Hard Card')], max_length=20, verbose_name='Document Type'),
        ),
        migrations.AlterField(
            model_name='historicaldocument',
            name='file',
            field=models.TextField(max_length=100, null=True, verbose_name='File'),
        ),
    ]
