# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-24 21:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import documents.models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_auto_20180324_1454'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(blank=True, null=True, verbose_name='Golf Season')),
                ('month', models.CharField(max_length=12, verbose_name='Month')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('portal_url', models.CharField(blank=True, max_length=200, verbose_name='Portal URL')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_type', models.CharField(choices=[('GC', 'Golf Course Photos'), ('EW', 'Event Winners'), ('EP', 'Event Photos'), ('O', 'Other')], max_length=2, verbose_name='Type')),
                ('year', models.IntegerField(default=0, verbose_name='Golf Season')),
                ('title', models.CharField(max_length=120, verbose_name='Title')),
                ('raw_image', models.ImageField(upload_to=documents.models.photo_directory_path, verbose_name='Image')),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='documents.Event', verbose_name='Event')),
            ],
        ),
        migrations.CreateModel(
            name='PhotoTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.Photo', verbose_name='Photo')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.Tag', verbose_name='Tag')),
            ],
        ),
        migrations.AlterField(
            model_name='document',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='documents.Event', verbose_name='Event'),
        ),
    ]
