# Generated by Django 5.1.4 on 2025-01-04 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_alter_document_document_type_alter_document_file_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicaldocument',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical document', 'verbose_name_plural': 'historical documents'},
        ),
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('ByLaws', 'ByLaws'), ('Club Registration', 'Club Registration'), ('Registration', 'Registration'), ('Results', 'Results'), ('Agenda', 'Agenda'), ('Minutes', 'Minutes'), ('Match Play', 'Match Play'), ('Match Play Brackets', 'Match Play Brackets'), ('Financial', 'Financial'), ('Standing Orders', 'Standing Orders'), ('Tee Times', 'Tee Times'), ('Other', 'Other'), ('Hard Card', 'Hard Card'), ('Past Presidents', 'Past Presidents')], max_length=20, verbose_name='Document Type'),
        ),
        migrations.AlterField(
            model_name='historicaldocument',
            name='document_type',
            field=models.CharField(choices=[('ByLaws', 'ByLaws'), ('Club Registration', 'Club Registration'), ('Registration', 'Registration'), ('Results', 'Results'), ('Agenda', 'Agenda'), ('Minutes', 'Minutes'), ('Match Play', 'Match Play'), ('Match Play Brackets', 'Match Play Brackets'), ('Financial', 'Financial'), ('Standing Orders', 'Standing Orders'), ('Tee Times', 'Tee Times'), ('Other', 'Other'), ('Hard Card', 'Hard Card'), ('Past Presidents', 'Past Presidents')], max_length=20, verbose_name='Document Type'),
        ),
        migrations.AlterField(
            model_name='historicaldocument',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.DeleteModel(
            name='HistoricalPhoto',
        ),
    ]
