# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-24 21:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0013_auto_20180320_1955'),
        ('documents', '0004_auto_20180324_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clubs.GolfCourse', verbose_name='Location'),
        ),
    ]
