# Generated by Django 2.1.2 on 2019-01-12 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_auto_20181228_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('Admin', 'Admin'), ('ByLaws', 'ByLaws'), ('Club Registration', 'Club Registration'), ('Registration', 'Registration'), ('Results', 'Results'), ('Meeting', 'Meeting'), ('Match Play', 'Match Play'), ('Match Play Brackets', 'Match Play Brackets'), ('Financial', 'Financial'), ('Communications', 'Communications'), ('Other', 'Other')], max_length=20, verbose_name='Document Type'),
        ),
        migrations.AlterField(
            model_name='historicaldocument',
            name='document_type',
            field=models.CharField(choices=[('Admin', 'Admin'), ('ByLaws', 'ByLaws'), ('Club Registration', 'Club Registration'), ('Registration', 'Registration'), ('Results', 'Results'), ('Meeting', 'Meeting'), ('Match Play', 'Match Play'), ('Match Play Brackets', 'Match Play Brackets'), ('Financial', 'Financial'), ('Communications', 'Communications'), ('Other', 'Other')], max_length=20, verbose_name='Document Type'),
        ),
    ]
