# Generated by Django 2.1.5 on 2020-01-19 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_auto_20190112_1655'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Application', 'Application'), ('ByLaws', 'ByLaws'), ('Club Registration', 'Club Registration'), ('Registration', 'Registration'), ('Results', 'Results'), ('Meeting', 'Meeting'), ('Match Play', 'Match Play'), ('Match Play Brackets', 'Match Play Brackets'), ('Financial', 'Financial'), ('Communications', 'Communications'), ('Other', 'Other')], max_length=20, verbose_name='Document Type'),
        ),
        migrations.AlterField(
            model_name='historicaldocument',
            name='document_type',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Application', 'Application'), ('ByLaws', 'ByLaws'), ('Club Registration', 'Club Registration'), ('Registration', 'Registration'), ('Results', 'Results'), ('Meeting', 'Meeting'), ('Match Play', 'Match Play'), ('Match Play Brackets', 'Match Play Brackets'), ('Financial', 'Financial'), ('Communications', 'Communications'), ('Other', 'Other')], max_length=20, verbose_name='Document Type'),
        ),
        migrations.AlterField(
            model_name='historicaldocument',
            name='tournament',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='events.Tournament', verbose_name='Tournament'),
        ),
        migrations.AlterField(
            model_name='historicalphoto',
            name='tournament',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='events.Tournament', verbose_name='Tournament'),
        ),
    ]
