# Generated by Django 2.1.5 on 2020-04-05 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0008_auto_20200119_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('ByLaws', 'ByLaws'), ('Registration', 'Registration'), ('Results', 'Results'), ('Agenda', 'Agenda'), ('Minutes', 'Minutes'), ('Match Play', 'Match Play'), ('Match Play Brackets', 'Match Play Brackets'), ('Financial', 'Financial'), ('Standing Orders', 'Standing Orders'), ('Tee Times', 'Tee Times'), ('Other', 'Other')], max_length=20, verbose_name='Document Type'),
        ),
        migrations.AlterField(
            model_name='historicaldocument',
            name='document_type',
            field=models.CharField(choices=[('ByLaws', 'ByLaws'), ('Registration', 'Registration'), ('Results', 'Results'), ('Agenda', 'Agenda'), ('Minutes', 'Minutes'), ('Match Play', 'Match Play'), ('Match Play Brackets', 'Match Play Brackets'), ('Financial', 'Financial'), ('Standing Orders', 'Standing Orders'), ('Tee Times', 'Tee Times'), ('Other', 'Other')], max_length=20, verbose_name='Document Type'),
        ),
    ]
