# Generated by Django 2.1.2 on 2018-10-14 21:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('clubs', '0001_initial'),
        ('events', '0003_auto_20181014_1645'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalParticipant',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('last_name', models.CharField(max_length=30, verbose_name='Last name')),
                ('first_name', models.CharField(max_length=30, verbose_name='First name')),
                ('email', models.CharField(max_length=240, verbose_name='Player email')),
                ('ghin', models.CharField(max_length=7, verbose_name='GHIN')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_date', models.DateTimeField()),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('home_club', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='clubs.Club')),
                ('member', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.Member')),
            ],
            options={
                'verbose_name': 'historical participant',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=30, verbose_name='Last name')),
                ('first_name', models.CharField(max_length=30, verbose_name='First name')),
                ('email', models.CharField(max_length=240, verbose_name='Player email')),
                ('ghin', models.CharField(max_length=7, verbose_name='GHIN')),
                ('home_club', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='clubs.Club', verbose_name='Home club')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.Member', verbose_name='Member')),
            ],
        ),
        migrations.RemoveField(
            model_name='historicalregistration',
            name='member',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='member',
        ),
        migrations.AddField(
            model_name='historicalregistrationgroup',
            name='division',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='events.EventDivision'),
        ),
        migrations.AddField(
            model_name='registrationgroup',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='events.EventDivision', verbose_name='Division'),
        ),
        migrations.AlterField(
            model_name='historicalregistration',
            name='event_fee',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='events.EventFee'),
        ),
        migrations.AlterField(
            model_name='historicalregistrationgroup',
            name='signed_up_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='register.Participant'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='event_fee',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='events.EventFee', verbose_name='Event fee'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='registrationgroup',
            name='signed_up_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='register.Participant', verbose_name='Signed up by'),
        ),
        migrations.AddField(
            model_name='historicalregistration',
            name='participant',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='register.Participant'),
        ),
        migrations.AddField(
            model_name='registration',
            name='participant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='register.Participant', verbose_name='Player'),
        ),
    ]
