# Generated by Django 2.1.2 on 2018-10-20 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_auto_20181014_1645'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalregistrationgroup',
            name='signed_up_by',
        ),
        migrations.RemoveField(
            model_name='registrationgroup',
            name='signed_up_by',
        ),
        migrations.AddField(
            model_name='historicalregistrationgroup',
            name='registered_by',
            field=models.CharField(default='unknown', max_length=60, verbose_name='Registered_by'),
        ),
        migrations.AddField(
            model_name='registrationgroup',
            name='registered_by',
            field=models.CharField(default='unknown', max_length=60, verbose_name='Registered_by'),
        ),
    ]
