# Generated by Django 2.1.2 on 2018-10-05 02:51

from django.db import migrations, models
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_url', models.CharField(blank=True, max_length=255, verbose_name='External url')),
                ('external_name', models.CharField(blank=True, max_length=40, verbose_name='External url name')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('text', models.TextField(verbose_name='Announcement text')),
                ('starts', models.DateTimeField(verbose_name='Display start')),
                ('expires', models.DateTimeField(verbose_name='Display expiration')),
            ],
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='Full name')),
                ('email', models.CharField(max_length=254, verbose_name='Email')),
                ('message_text', models.TextField(verbose_name='Message text')),
                ('message_date', models.DateTimeField(auto_now_add=True, verbose_name='Message date')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalAnnouncement',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('external_url', models.CharField(blank=True, max_length=255, verbose_name='External url')),
                ('external_name', models.CharField(blank=True, max_length=40, verbose_name='External url name')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('text', models.TextField(verbose_name='Announcement text')),
                ('starts', models.DateTimeField(verbose_name='Display start')),
                ('expires', models.DateTimeField(verbose_name='Display expiration')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_date', models.DateTimeField()),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical announcement',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
