# Generated by Django 3.0.6 on 2020-05-10 22:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        ('documents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(max_length=30, verbose_name='Message type')),
                ('course', models.CharField(blank=True, max_length=100, null=True, verbose_name='Golf course')),
                ('contact_name', models.CharField(max_length=100, verbose_name='Contact name')),
                ('contact_email', models.CharField(max_length=254, verbose_name='Contact email')),
                ('contact_phone', models.CharField(blank=True, max_length=20, verbose_name='Contact phone')),
                ('event', models.CharField(blank=True, max_length=120, null=True, verbose_name='Event name')),
                ('message', models.TextField(verbose_name='Message')),
                ('message_date', models.DateTimeField(auto_now_add=True, verbose_name='Message date')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalContactMessage',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('message_type', models.CharField(max_length=30, verbose_name='Message type')),
                ('course', models.CharField(blank=True, max_length=100, null=True, verbose_name='Golf course')),
                ('contact_name', models.CharField(max_length=100, verbose_name='Contact name')),
                ('contact_email', models.CharField(max_length=254, verbose_name='Contact email')),
                ('contact_phone', models.CharField(blank=True, max_length=20, verbose_name='Contact phone')),
                ('event', models.CharField(blank=True, max_length=120, null=True, verbose_name='Event name')),
                ('message', models.TextField(verbose_name='Message')),
                ('message_date', models.DateTimeField(blank=True, editable=False, verbose_name='Message date')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical contact message',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalAnnouncement',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('external_url', models.CharField(blank=True, max_length=255, verbose_name='External url')),
                ('external_name', models.CharField(blank=True, max_length=40, verbose_name='External url name')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('text', models.TextField(verbose_name='Announcement text')),
                ('starts', models.DateTimeField(verbose_name='Display start')),
                ('expires', models.DateTimeField(verbose_name='Display expiration')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('document', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='documents.Document', verbose_name='Document')),
                ('event', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='events.Event', verbose_name='Event')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical announcement',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_url', models.CharField(blank=True, max_length=255, verbose_name='External url')),
                ('external_name', models.CharField(blank=True, max_length=40, verbose_name='External url name')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('text', models.TextField(verbose_name='Announcement text')),
                ('starts', models.DateTimeField(verbose_name='Display start')),
                ('expires', models.DateTimeField(verbose_name='Display expiration')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='documents.Document', verbose_name='Document')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='events.Event', verbose_name='Event')),
            ],
        ),
    ]
