# Generated by Django 5.1.4 on 2025-01-04 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalannouncement',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical announcement', 'verbose_name_plural': 'historical announcements'},
        ),
        migrations.AlterModelOptions(
            name='historicalcontactmessage',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical contact message', 'verbose_name_plural': 'historical contact messages'},
        ),
        migrations.AlterField(
            model_name='historicalannouncement',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalcontactmessage',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
    ]
