# Generated by Django 2.1.2 on 2018-12-15 22:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('communication', '0002_auto_20181004_2151'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalContactMessage',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('message_type', models.CharField(max_length=30, verbose_name='Message type')),
                ('course', models.CharField(blank=True, max_length=100, null=True, verbose_name='Golf course')),
                ('contact_name', models.CharField(max_length=100, verbose_name='Contact name')),
                ('contact_email', models.CharField(max_length=254, verbose_name='Contact email')),
                ('contact_phone', models.CharField(max_length=20, verbose_name='Contact phone')),
                ('season', models.IntegerField(blank=True, null=True, verbose_name='Golf season')),
                ('message', models.TextField(verbose_name='Message')),
                ('message_date', models.DateTimeField(blank=True, editable=False, verbose_name='Message date')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_date', models.DateTimeField()),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical contact message',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.RemoveField(
            model_name='contactmessage',
            name='email',
        ),
        migrations.RemoveField(
            model_name='contactmessage',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='contactmessage',
            name='message_text',
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='contact_email',
            field=models.CharField(default='', max_length=254, verbose_name='Contact email'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='contact_name',
            field=models.CharField(default='', max_length=100, verbose_name='Contact name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='contact_phone',
            field=models.CharField(default='', max_length=20, verbose_name='Contact phone'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='course',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Golf course'),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='message',
            field=models.TextField(default='', verbose_name='Message'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='message_type',
            field=models.CharField(default='', max_length=30, verbose_name='Message type'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='season',
            field=models.IntegerField(blank=True, null=True, verbose_name='Golf season'),
        ),
    ]
