# Generated by Django 2.1.2 on 2018-12-27 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0003_auto_20181215_1600'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactmessage',
            name='season',
        ),
        migrations.RemoveField(
            model_name='historicalcontactmessage',
            name='season',
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='event',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Event name'),
        ),
        migrations.AddField(
            model_name='historicalcontactmessage',
            name='event',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Event name'),
        ),
    ]
