# Generated by Django 2.1.5 on 2020-01-19 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0004_auto_20181227_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalannouncement',
            name='document',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='documents.Document', verbose_name='Document'),
        ),
        migrations.AlterField(
            model_name='historicalannouncement',
            name='event',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='events.Event', verbose_name='Event'),
        ),
    ]
