# Generated by Django 2.1.5 on 2020-04-05 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0005_auto_20200119_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Contact phone'),
        ),
        migrations.AlterField(
            model_name='historicalcontactmessage',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Contact phone'),
        ),
    ]
