# Generated by Django 2.0.1 on 2018-01-13 23:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_txt', models.CharField(max_length=200, verbose_name='Street Address')),
                ('city', models.CharField(max_length=40, verbose_name='City')),
                ('state', models.CharField(max_length=2, verbose_name='State')),
                ('zip', models.CharField(max_length=10, verbose_name='Zip Code')),
            ],
        ),
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Club Name')),
                ('website', models.CharField(blank=True, max_length=300, verbose_name='Website')),
                ('club_email', models.CharField(blank=True, max_length=250, verbose_name='Club Email')),
                ('club_phone', models.CharField(blank=True, max_length=20, verbose_name='Club Phone')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
            ],
        ),
        migrations.CreateModel(
            name='ClubContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=30, verbose_name='Role')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='clubs.Club', verbose_name='Club')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=30, verbose_name='Last Name')),
                ('primary_phone', models.CharField(blank=True, max_length=20, verbose_name='Primary Phone')),
                ('alternate_phone', models.CharField(blank=True, max_length=20, verbose_name='Alternate Phone')),
                ('email', models.CharField(blank=True, max_length=250, verbose_name='Email')),
                ('mailing_address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='clubs.Address', verbose_name='Mailing Address')),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Golf Season')),
                ('payment_date', models.DateField(verbose_name='Payment Date')),
                ('payment_type', models.CharField(max_length=20, verbose_name='Payment Type')),
                ('payment_code', models.CharField(blank=True, max_length=20, verbose_name='Code or Number')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Date Recorded')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='clubs.Club', verbose_name='Club')),
            ],
        ),
        migrations.AddField(
            model_name='clubcontact',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='clubs.Contact', verbose_name='Contact'),
        ),
        migrations.AddField(
            model_name='club',
            name='contacts',
            field=models.ManyToManyField(through='clubs.ClubContact', to='clubs.Contact', verbose_name='Contacts'),
        ),
        migrations.AddField(
            model_name='club',
            name='mailing_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='clubs.Address', verbose_name='Mailing Address'),
        ),
    ]
