# Generated by Django 2.1.2 on 2018-10-19 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubContactRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('Director of Golf', 'Director of Golf'), ('Event Director', 'Event Director'), ('General Manager', 'General Manager'), ('Handicap Chair', 'Handicap Chair'), ('Manager', 'Manager'), ('Match Play Captain', 'Match Play Captain'), ("Men's Club Contact", "Men's Club Contact"), ("Men's Club President", "Men's Club President"), ("Men's Club Secretary", "Men's Club Secretary"), ("Men's Club Treasurer", "Men's Club Treasurer"), ('Owner', 'Owner'), ('PGA Professional', 'PGA Professional'), ('Sr. Match Play Captain', 'Sr. Match Play Captain'), ('Superintendent', 'Superintendent'), ('Tournament Player', 'Tournament Player'), ('Other', 'Other')], max_length=30, verbose_name='Role')),
                ('club_contact', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='roles', to='clubs.ClubContact', verbose_name='Club Contact')),
            ],
        ),
        migrations.AddField(
            model_name='team',
            name='contact2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='co_captain', to='clubs.Contact', verbose_name='Co-Captain'),
        ),
        migrations.AlterField(
            model_name='team',
            name='contact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='captain', to='clubs.Contact', verbose_name='Captain'),
        ),
    ]
