# Generated by Django 2.0.1 on 2018-01-14 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='mailing_address',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='mailing_address',
        ),
        migrations.AddField(
            model_name='club',
            name='address_txt',
            field=models.CharField(blank=True, max_length=200, verbose_name='Street Address'),
        ),
        migrations.AddField(
            model_name='club',
            name='city',
            field=models.CharField(blank=True, max_length=40, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='club',
            name='state',
            field=models.CharField(blank=True, choices=[('MN', 'Minnesota'), ('WI', 'Wisconsin')], default='MN', max_length=2, verbose_name='State'),
        ),
        migrations.AddField(
            model_name='club',
            name='zip',
            field=models.CharField(blank=True, max_length=10, verbose_name='Zip Code'),
        ),
        migrations.DeleteModel(
            name='Address',
        ),
    ]
