# Generated by Django 2.1.2 on 2018-10-20 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_auto_20181019_0825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubcontact',
            name='role',
            field=models.CharField(choices=[('Director of Golf', 'Director of Golf'), ('Event Director', 'Event Director'), ('General Manager', 'General Manager'), ('Handicap Chair', 'Handicap Chair'), ('Manager', 'Manager'), ('Match Play Captain', 'Match Play Captain'), ("Men's Club Contact", "Men's Club Contact"), ("Men's Club President", "Men's Club President"), ("Men's Club President", "Men's Club Past-President"), ("Men's Club Secretary", "Men's Club Secretary"), ("Men's Club Treasurer", "Men's Club Treasurer"), ('Owner', 'Owner'), ('PGA Professional', 'PGA Professional'), ('Sr. Match Play Captain', 'Sr. Match Play Captain'), ('Superintendent', 'Superintendent'), ('Other', 'Other')], max_length=30, verbose_name='Role'),
        ),
        migrations.AlterField(
            model_name='clubcontactrole',
            name='role',
            field=models.CharField(choices=[('Director of Golf', 'Director of Golf'), ('Event Director', 'Event Director'), ('General Manager', 'General Manager'), ('Handicap Chair', 'Handicap Chair'), ('Manager', 'Manager'), ('Match Play Captain', 'Match Play Captain'), ("Men's Club Contact", "Men's Club Contact"), ("Men's Club President", "Men's Club President"), ("Men's Club President", "Men's Club Past-President"), ("Men's Club Secretary", "Men's Club Secretary"), ("Men's Club Treasurer", "Men's Club Treasurer"), ('Owner', 'Owner'), ('PGA Professional', 'PGA Professional'), ('Sr. Match Play Captain', 'Sr. Match Play Captain'), ('Superintendent', 'Superintendent'), ('Other', 'Other')], max_length=30, verbose_name='Role'),
        ),
    ]
