# Generated by Django 2.0.1 on 2018-01-14 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_auto_20180114_0841'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='type_2',
            field=models.BooleanField(default=False, verbose_name='Type 2'),
        ),
    ]
