# Generated by Django 5.1.4 on 2025-01-19 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_clubrole_alter_clubcontactrole_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='archived',
            field=models.BooleanField(default=False, verbose_name='Archived'),
        ),
    ]
