# Generated by Django 2.0.1 on 2018-01-14 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0003_club_type_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubcontact',
            name='is_primary',
            field=models.BooleanField(default=False, verbose_name='Primary Contact'),
        ),
        migrations.AddField(
            model_name='contact',
            name='contact_type',
            field=models.CharField(choices=[('MC', "Men's Club"), ('PGA', 'PGA Professional'), ('MGR', 'Manager or General Manager'), ('DOG', 'Director of Golf'), ('UNK', 'Unknown')], default='UNK', max_length=3, verbose_name='Contact Type'),
        ),
    ]
