# Generated by Django 2.1.2 on 2018-12-25 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0004_auto_20181215_1600'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clubcontact',
            name='role',
        ),
        migrations.RemoveField(
            model_name='team',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='team',
            name='contact2',
        ),
        migrations.AddField(
            model_name='clubcontact',
            name='notes',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='contact_type',
            field=models.CharField(choices=[("Men's Club", "Men's Club"), ('Facilities', 'Facilities')], default="Men's Club", max_length=20, verbose_name='Contact Type'),
        ),
    ]
