# Generated by Django 2.1.2 on 2018-12-28 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0005_auto_20181225_1607'),
    ]

    operations = [
        migrations.CreateModel(
            name='Affiliate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.CharField(max_length=60, verbose_name='Organization')),
                ('website', models.CharField(max_length=240, verbose_name='Website')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
            ],
        ),
        migrations.CreateModel(
            name='Committee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=40, verbose_name='Role')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='clubs.Contact', verbose_name='Contact')),
                ('home_club', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='clubs.Club', verbose_name='Home Club')),
            ],
            options={
                'verbose_name': 'Executive Committee',
                'verbose_name_plural': 'Executive Committee',
            },
        ),
    ]
