# Generated by Django 2.1.2 on 2018-12-28 19:53

import clubs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0006_affiliate_committee'),
    ]

    operations = [
        migrations.AddField(
            model_name='golfcourse',
            name='logo',
            field=models.ImageField(default=0, upload_to=clubs.models.photo_directory_path, verbose_name='Logo'),
            preserve_default=False,
        ),
    ]
