# Generated by Django 2.0.1 on 2018-01-15 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0006_auto_20180114_1157'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Golf Season')),
                ('group_name', models.CharField(max_length=20, verbose_name='Group')),
                ('is_senior', models.BooleanField(verbose_name='Senior')),
            ],
        ),
        migrations.AlterModelOptions(
            name='club',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='clubcontact',
            name='role',
            field=models.CharField(choices=[('Director of Golf', 'Director of Golf'), ('General Manager', 'General Manager'), ('Handicap Chair', 'Handicap Chair'), ('Manager', 'Manager'), ('Match Play Captain', 'Match Play Captain'), ("Men's Club Contact", "Men's Club Contact"), ("Men's Club President", "Men's Club President"), ("Men's Club Secretary", "Men's Club Secretary"), ("Men's Club Treasurer", "Men's Club Treasurer"), ('Owner', 'Owner'), ('PGA Professional', 'PGA Professional'), ('Sr. Match Play Captain', 'Sr. Match Play Captain')], max_length=30, verbose_name='Role'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='payment_type',
            field=models.CharField(choices=[('CK', 'Check'), ('OL', 'Online'), ('CA', 'Cash')], default='CK', max_length=2, verbose_name='Payment Type'),
        ),
        migrations.AddField(
            model_name='team',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='teams', to='clubs.Club', verbose_name='Club'),
        ),
    ]
