# Generated by Django 2.1.2 on 2018-12-28 20:17

import clubs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0007_golfcourse_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='golfcourse',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=clubs.models.photo_directory_path, verbose_name='Logo'),
        ),
    ]
