# Generated by Django 2.0.1 on 2018-01-15 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0007_auto_20180115_0717'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='contact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='clubs.Contact', verbose_name='Captain'),
        ),
    ]
