# Generated by Django 2.1.2 on 2018-12-30 17:30

import clubs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0008_auto_20181228_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='golfcourse',
            name='logo',
            field=models.ImageField(default='', upload_to=clubs.models.photo_directory_path, verbose_name='Logo'),
            preserve_default=False,
        ),
    ]
