# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-20 23:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0010_auto_20180320_1801'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactImport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=30, verbose_name='Last Name')),
                ('address_txt', models.CharField(blank=True, max_length=200, verbose_name='Street Address')),
                ('city', models.CharField(blank=True, max_length=40, verbose_name='City')),
                ('state', models.CharField(blank=True, choices=[('MN', 'Minnesota'), ('WI', 'Wisconsin')], default='MN', max_length=2, verbose_name='State')),
                ('zip', models.CharField(blank=True, max_length=10, verbose_name='Zip Code')),
            ],
        ),
    ]
