# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-21 00:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0011_contactimport'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='golf_course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='clubs.GolfCourse', verbose_name='Home Course'),
        ),
        migrations.AlterField(
            model_name='club',
            name='state',
            field=models.CharField(blank=True, choices=[('IA', 'Iowa'), ('MN', 'Minnesota'), ('ND', 'North Dakota'), ('SD', 'South Dakota'), ('WI', 'Wisconsin')], default='MN', max_length=2, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='state',
            field=models.CharField(blank=True, choices=[('IA', 'Iowa'), ('MN', 'Minnesota'), ('ND', 'North Dakota'), ('SD', 'South Dakota'), ('WI', 'Wisconsin')], default='MN', max_length=2, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='contactimport',
            name='state',
            field=models.CharField(blank=True, choices=[('IA', 'Iowa'), ('MN', 'Minnesota'), ('ND', 'North Dakota'), ('SD', 'South Dakota'), ('WI', 'Wisconsin')], default='MN', max_length=2, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='golfcourse',
            name='state',
            field=models.CharField(blank=True, choices=[('IA', 'Iowa'), ('MN', 'Minnesota'), ('ND', 'North Dakota'), ('SD', 'South Dakota'), ('WI', 'Wisconsin')], default='MN', max_length=2, verbose_name='State'),
        ),
    ]
