# Generated by Django 2.1.2 on 2019-01-01 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0011_auto_20190101_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='payment_code',
            field=models.CharField(blank=True, max_length=100, verbose_name='Code or Number'),
        ),
    ]
