# Generated by Django 2.1.2 on 2019-01-06 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0012_auto_20190101_1705'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchPlayResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=20, verbose_name='Group')),
                ('match_date', models.DateField(verbose_name='Date Played')),
                ('home_team_score', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='Home Team Score')),
                ('away_team_score', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='Away Team Score')),
                ('entered_by', models.CharField(max_length=60, verbose_name='Entered By')),
                ('forfeit', models.BooleanField(verbose_name='Forfeit')),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='away_team', to='clubs.Club', verbose_name='Away Team')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='home_team', to='clubs.Club', verbose_name='Home Team')),
            ],
            options={
                'ordering': ['group_name', 'match_date'],
            },
        ),
    ]
