# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-21 00:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0012_auto_20180320_1912'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='use_as_primary',
        ),
        migrations.AddField(
            model_name='clubcontact',
            name='use_for_mailings',
            field=models.BooleanField(default=False, verbose_name='Use for Club Mailings'),
        ),
        migrations.AlterField(
            model_name='club',
            name='golf_course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='clubs.GolfCourse', verbose_name='Home Course'),
        ),
    ]
