# Generated by Django 2.1.2 on 2019-01-12 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0013_matchplayresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchplayresult',
            name='notes',
            field=models.CharField(blank=True, max_length=140, null=True, verbose_name='Notes'),
        ),
    ]
