# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-01 23:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0014_contact_notes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactImport',
        ),
        migrations.AddField(
            model_name='team',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='clubcontact',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='club_to_contact', to='clubs.Club', verbose_name='Club'),
        ),
        migrations.AlterField(
            model_name='clubcontact',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='contact_to_club', to='clubs.Contact', verbose_name='Contact'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='memberships', to='clubs.Club', verbose_name='Club'),
        ),
    ]
