# Generated by Django 2.1.2 on 2019-01-13 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0015_club_short_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='matchplayresult',
            options={'ordering': ['-match_date', 'group_name']},
        ),
    ]
