# Generated by Django 2.1.5 on 2020-02-02 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0018_auto_20200119_1346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='short_name',
        ),
        migrations.AddField(
            model_name='club',
            name='system_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='System name'),
        ),
    ]
