# Generated by Django 2.1.5 on 2020-03-01 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0019_auto_20200202_1101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='contact_type',
        ),
    ]
