# Generated by Django 2.1.5 on 2020-04-10 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0020_remove_contact_contact_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubcontact',
            name='send_email',
            field=models.BooleanField(default=False, verbose_name='Send Email'),
        ),
    ]
