# Generated by Django 2.1.5 on 2020-04-11 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0021_clubcontact_send_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='type_2',
        ),
        migrations.RemoveField(
            model_name='clubcontact',
            name='send_email',
        ),
        migrations.AddField(
            model_name='contact',
            name='home_club',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Club Name'),
        ),
        migrations.AddField(
            model_name='contact',
            name='send_email',
            field=models.BooleanField(default=False, verbose_name='Send Email'),
        ),
    ]
